CHANGELOG.md, pom.xml, src/main/java/de/samply/share/client/control/UserBean.java, src/main/java/de/samply/share/client/crypt/Crypt.java, src/main/java/de/samply/share/client/fhir/FhirResource.java, src/main/java/de/samply/share/client/messages/messages_de.properties, src/main/java/de/samply/share/client/rest/Api.java, src/main/java/de/samply/share/client/util/connector/CtsConnector.java, src/main/java/de/samply/share/client/util/connector/MainzellisteConnector.java
send pseudonymised bundle as JSON only
renamed some methods
=> send pseudonymised bundle as JSON only

.dockerignore, Dockerfile
* Rather than unpacking .war at each start, unpack once during docker build.
**How to test manually**
* Build as usual, see that Connector is executed. Actual code is unchanged.
=> Unpack war file in docker image to accelerate startup.

CHANGELOG.md, pom.xml, src/main/java/de/samply/share/client/control/BrokerBean.java, src/main/java/de/samply/share/client/util/connector/BrokerConnector.java, src/main/webapp/admin/broker_list.xhtml
- parent pom 11.1.1
- show error message from setSite()
=> Parent Pom 11.1.1

pom.xml
We never had a v7.3.1 released.
=> Revert Version to v7.3.0-SNAPSHOT

src/main/java/de/samply/share/client/quality/report/logger/PercentageLogger.java
Only negative numbers of elements should be invalid.
=> Fix Number of Elements Check in PercentageLogger

src/docker/log4j2.xml
The property was not resolved. In addition to removing the property, I use the better performing pattern from Moanes.
=> Fix Log4J Pattern

src/main/java/de/samply/share/client/quality/report/file/excel/workbook/ExcelWorkbookFactoryImpl002.java
Constants only used in the same class should be private.
=> Make Constants Private

src/main/java/de/samply/share/client/control/ApplicationBean.java, src/main/java/de/samply/share/client/util/connector/LdmConnectorCentraxx.java
timeout 3*60 in application bean
* Check connection timeout with ldm
=> use authorization for ldm in centraxx

CHANGELOG.md, src/main/java/de/samply/share/client/control/InquiryBean.java
* Add timestamp to last export filename
=> add timestamp to last export filename

docs/deployment/docker-deployment.md, src/docker/samply_common_config.xml, src/docker/start.sh
* Renamed the proxy variables (old should still work, but with a warning at container startup)
* Added additional HTTPS_* environement variables
* Added NO_PROXY_HOSTS environment variable
=> Added separate proxy configuration for https proxies

CHANGELOG.md, pom.xml, src/main/java/de/samply/share/client/util/connector/BrokerConnector.java
added redirect url for the negotiator
=> added redirect url for the negotiator

src/main/resources/db/migration/V033__common_add_report_to_monitoring_24h.sql, src/main/resources/db/migration_legacy/dktk/V003__initial_dml.sql, src/main/resources/db/migration_legacy/dktk/V009__config.sql, src/main/resources/db/migration_legacy/samply/V002__initialize_configuration.sql
bugfix: reporttomonitoringjob. update name in DB (short and long frequence)
=> fix bug: report to monitoring job short and long frecuence

.github/workflows/ci.yml, .github/workflows/sonar.yml, CHANGELOG.md, pom.xml
=> log4j 2.16.0

CHANGELOG.md, pom.xml
increase log4j version to 2.17,0
=> log4j version 2.17.0

CHANGELOG.md, pom.xml
=> log4j 2.17.1

src/main/webapp/WEB-INF/templates/globalTemplate.xhtml, src/main/webapp/WEB-INF/templates/layout.xhtml
=> fixed jquery-ui.min error

CHANGELOG.md, pom.xml
=> version 7.5.0-SNAPSHOT

pom.xml, src/main/webapp/WEB-INF/templates/globalTemplate.xhtml, src/main/webapp/WEB-INF/templates/layout.xhtml, src/main/webapp/index.xhtml, src/main/webapp/login.xhtml
* Update frontend libraries in xhtml. It was forgotten in the last PR.
=> update frontend libraries

src/main/java/de/samply/share/client/job/UploadToCentralMdsDbJob.java, src/main/java/de/samply/share/client/util/connector/BrokerConnector.java, src/main/java/de/samply/share/client/util/connector/LdmConnectorCentraxx.java, src/main/java/de/samply/share/client/util/connector/MainzellisteConnector.java, src/main/java/de/samply/share/client/util/connector/centraxx/CxxMappingParser.java
* Update way, in which JsonParser is called. Previous way is deprecated.
=> Remove Deprecated Usage of Gson JsonParser Constructor Call

pom.xml, src/main/java/de/samply/share/client/model/centralsearch/UploadStats.java, src/main/java/de/samply/share/client/util/connector/CentralSearchConnector.java, src/test/java/de/samply/share/client/model/centralsearch/UploadStatsTest.java
* Serialize and deserialize upload test through Jackarta XmlMapper
=> Replace simple-xml-safe Dependency with Jackson XML

CHANGELOG.md, pom.xml, src/main/java/de/samply/share/client/listener/StartupListener.java
* Hotfix: Initialize log4j config with log4j2.xml
=> Initialize log4j with log4j2.xml

CHANGELOG.md, pom.xml, src/main/java/de/samply/share/client/control/BrokerBean.java
Bug at the Searchbroker registration when typing two times unreachable urls
=> fixed searchbroker registration bug

CHANGELOG.md, pom.xml, src/main/webapp/WEB-INF/templates/globalTemplate.xhtml, src/main/webapp/user/inquiries_list.xhtml
fix jsf problems with jersey 3
=> Bugfix: Add Jersey 1 libraries for JSF 2

pom.xml
Merge Release 7.6.1 with develop, increase version and set to SNAPSHOT
=> Version 7.6.2-SNAPSHOT

CHANGELOG.md, src/main/java/de/samply/share/client/control/ConfigurationBean.java, src/main/java/de/samply/share/client/messages/messages_de.properties, src/main/java/de/samply/share/client/messages/messages_en.properties, src/main/webapp/WEB-INF/includes/c_configuration_centralMdsDb.xhtml, src/main/webapp/WEB-INF/includes/c_configuration_interfaces.xhtml, src/main/webapp/WEB-INF/includes/c_configuration_misc.xhtml, src/main/webapp/WEB-INF/includes/c_configuration_monitoring.xhtml, src/main/webapp/WEB-INF/includes/c_configuration_timings.xhtml, src/main/webapp/admin/broker_list.xhtml, src/main/webapp/admin/configuration.xhtml, src/main/webapp/admin/credentials_list.xhtml, src/main/webapp/admin/user_list.xhtml, src/main/webapp/resources/css/samply-share.css, src/main/webapp/resources/js/pages/inquiries_list.js, src/main/webapp/user/inquiries_list.xhtml
* The Button that updates inquiries in the user interface
=> Add update button in inquiries_list.xhtml

pom.xml, src/main/java/de/samply/share/client/job/DirectorySyncJob.java
increased directory-sync version
=> increase directory-sync version

CHANGELOG.md, pom.xml
edited changelog
changed pom version
=> changed pom version

pom.xml
* ...
**How to test manually**
* ...
=> updated common-ldmclient.cql and common-ldmclient.centraxx versions

src/main/java/de/samply/share/client/control/InquiryBean.java, src/main/webapp/user/show_inquiry.xhtml
I have no idea what this sublist feature is. I only fixed the technical details that the list can be empty. I would also not use a list in the first place here. It looks more like a tuple to me.
=> Fix IndexOutOfBoundsException in SubList Feature

Dockerfile, GETTINGSTARTED.md
* Modified docker file for non root container
**How to test manually**
* spin up the container, ssh into it and check userid
=> Non root docker image
